image: registry.clarisys.fr/adm/sintls:latest
before_script:
  - sudo apt-get -qy update && sudo apt-get -qy install dh-golang golang-1.13 golang-go

binary:
  script:
    - make
    - mv sintls-client sintls-client_linux_amd64
    - mv sintls-server sintls-server_linux_amd64
    - sha256sum sintls-client_linux_amd64 > sintls-client_linux_amd64.sha256
    - sha256sum sintls-server_linux_amd64 > sintls-server_linux_amd64.sha256
  tags: ["linux"]
  artifacts:
    paths:
      - sintls-*_linux_amd64
      - sintls-*_linux_amd64.sha256

debian_package:
  variables:
    GOPROXY: https://proxy.golang.org
    GO111MODULE: on
    GOCACHE: /tmp/gocache
  script:
    - git status
    - git branch -a
    - gbp buildpackage
  tags: ["linux"]
  artifacts:
    paths:
      - tmp/*.deb
      - tmp/*.changes
      - tmp/*.tar.*
      - tmp/*.dsc
