language: go
go:
- 1.12.x

script:
- make
- "[ -d dist ] || mkdir dist"
- mv sintls-client dist/sintls-client_linux_amd64
- mv sintls-server dist/sintls-server_linux_amd64
- sha256sum dist/sintls-client_linux_amd64 > dist/sintls-client_linux_amd64.sha256
- sha256sum dist/sintls-server_linux_amd64 > dist/sintls-server_linux_amd64.sha256
- sudo apt install git-buildpackage dh-golang
- GOCACHE=/tmp/gocache GBP_CONF_FILES=:debian/gbp.conf gbp buildpackage --git-ignore-branch --git-ignore-new --git-no-purge --git-export-dir=tmp --git-tarball-dir=/nonexistant --git-builder='dpkg-buildpackage -d --no-sign'

deploy:
  provider: releases
  api_key:
    secure: bPwB5PtNB86McdTuBFB4hS2MaiF6PRXmS7m2plbmVgcvm7BqZoSPG0XXqMtR7W7G/lpuoTMpHpZksaqDjLNWcnwxWpEmIMkpjrjHFgm3AtBa+5u6SVMJJKvf5XZFLvkfLRdRuNKbRkUFsravjglw8fMPdz5HcOJzjg8F5SXF2Mb+TLrzVRdUlB2LCcc2LuFUBEz6FBPSB3+/HWUOg7wKcCtv+o4it0tp4G7d1BpzOVCD5KUxs1Zr4gVUzHnPrJemwnAv8fygqIDVYXgrWT1AtvnW4DKcuxCI2VdO4iiBt6XIXlmj636gnuSgxawpgQYBKLMkdGVfOaBskCJs+SBXS2DBfZJLgnp6a6vDNKGDqkGlAveaFFD8k6NACWfmGH1Jrd0UY1iJIRIpg1UeN9RDOagkvGUCvEpB7GgqgAYewxHpfYqY7uvL23yGzWvm+S7NaMx8zyvJphrwkoy8lJKtQqbqBHR3U4bFT0xhWdTsA6Hg2Jqs2M1d3wCfNRWOkpskoxtA0P++Kb5cAIsX10uD8nF3ScD+Cpjn1Sk0pJYsK49/HiqK3cAP8RtzZoQqkoHM7dx3ih8fDxZORaInUn3tV6JtxVVz2AMrKt0N4zdGFSEFTtf6xMFKUyqn/jbokQjYoQOAwQPFkt8d18KIE2VCgQHZBWt4QqvAGJzLvIOAkxQ=
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    tags: true

env:
  - GO111MODULE=on
