dist: bionic
services:
  - docker
before_install:
  - docker pull zehome/sintls
  - mkdir -p tmp
jobs:
  include:
    - stage: "build"
      name: "Static binaries"
      script:
        - docker run --rm -it -v "$(realpath .):/tmp/sintls" -w /tmp/sintls zehome/sintls make OUTDIR=tmp release
        - sudo chown $(id -u):$(id -g) -R tmp
    - stage: "build"
      name: "Debian packages"
      script:
        - docker run -e GOPROXY="https://proxy.golang.org" -e GO111MODULE=on -e GOCACHE=/tmp/cache --rm -it -v "$(realpath .):/tmp/sintls" -w /tmp/sintls zehome/sintls gbp buildpackage
        - sudo chown $(id -u):$(id -g) -R tmp
before_deploy:
  - ls -al $TRAVIS_BUILD_DIR $TRAVIS_BUILD_DIR/tmp
deploy:
  provider: releases
  api_key:
    secure: "abwlRMAQBzP7Z4dXbBgofdHR94xJg46VrfJEgm1BLnLvTAuiW5MczxOZsCKVAhmbqDQXul90zk84mCRL8zazgdzNBP//FPQ4pZdlUcPJ9DIiC/CzWXBH2cdlu0irse8l+XsCiDNbeMB6xt1VnLE7ulszeWKv41kTNJBnM838tkFkiJWE2j2pUZVrqOoiHz+PZpML3nNdI402248AFQQH6vvxbW5nb+X/pHtXa7Ma+O/AJ9AZyvHR5nho00CaF79hY1i8AVae1zKYzWgVVUGbj34dH/xEEzMdvIJ58G/fiL5Cv2Sh0DVBs9DhJmvev6Nz5c3dXSJCCBSr3Fx8x3CZGWZjjqK39aRtMELE0A3Voct4DYjkzWJszBMrFstcnzViWEKQoSVNlqTcFIBM3uP8HVz8YCH50qlkDQgjr15w/SsCqrWi7sUg37Mnz3xXLZCfdIr9NptGOmyPnYOo+uqCopIKjiLwdRONNzloBnpH38cRz4IyXf7KWjj2acASQmoAPyHFl8U/u0svf4A5SUKAgDNM5/F0QwIdh7FjHB0ojeKKL0poEMEnMcHu5dfy8cC98Lg8aiGpbW1gdH89tlzNcabM3nCgXtiLNAjfeZkhiXoRJ8pThFpgzbyFx0SNLxLYFt5t19Er7DwdsLM0XXUoqifrf5bB/zb5uhha0IhocUs="
  file:
    - "$TRAVIS_BUILD_DIR/tmp/sintls_*"
    - "$TRAVIS_BUILD_DIR/tmp/sintls-client_*"
    - "$TRAVIS_BUILD_DIR/tmp/sintls-server_*"
    - README.md
  file_glob: true
  draft: true
  overwrite: true
  skip_cleanup: true
  cleanup: false
  on:
    repo: zehome/sintls
    tags: true
