language: go

go:
  - 1.12.x

script:
  - make
  - mv dist/sintls dist/sintls_linux_amd64
  - mv dist/sintlsserver dist/sintlsserver_linux_amd64
  - sha256sum dist/sintls_linux_amd64 > dist/sintls_linux_amd64.sha256
  - sha256sum dist/sintlsserver_linux_amd64 > dist/sintlsserver_linux_amd64.sha256

deploy:
  provider: releases
  api_key:
    secure: AAA
  file:
  	- dist/sintls_linux_amd64
    - dist/sintls_linux_amd64.sha256
  	- dist/sintlsserver_linux_amd64
    - dist/sintlsserver_linux_amd64.sha256
  skip_cleanup: true
  on:
    tags: true